# Generated by Django 3.0.3 on 2020-02-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200222_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearModel',
        ),
    ]
